# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171213_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='id',
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.CharField(default='anonimo', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='sentiment_card_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='student_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
