# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171220_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='student_id',
            field=models.CharField(max_length=200),
        ),
    ]
